# https://services.shopify.io/services/polaris-tokens/production
owners:
  - Shopify/polaris
production:
  classification: library
gem:
  classification: library
slack_channels:
  - polaris
  - polaris-help
