name: Automate project columns

on: [issues]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move new issues into Triage
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: ğŸŒŒ Polaris backlog
          column: ğŸ‘€ Triage
          repo-token: ${{ secrets.POLARIS_AUTOMATION_KAELIG }}

      - name: Move assinged issues into To do
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: ğŸŒŒ Polaris backlog
          column: ğŸ“ To do
          repo-token: ${{ secrets.POLARIS_AUTOMATION_KAELIG }}
